name: Работа в личном кабинете FulEx

navbar-links:
  Resources:
    - Оформление забора: 'https://fulexpro.github.io/measoft_client_docs/registration_cargo_pickup.html'
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"